name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta-linux
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/ucsd-cse123-fa23/pa2a-container
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: linux
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: ${{ steps.meta-linux.outputs.tags }}
          labels: ${{ steps.meta-linux.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker meta
        id: meta-windows
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/ucsd-cse123-fa23/pa2a-container
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=windows,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          target: windows
          platforms: 'linux/amd64'
          push: true
          tags: ${{ steps.meta-windows.outputs.tags }}
          labels: ${{ steps.meta-windows.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
